### PR TITLE
Disable caching for BuildPluginTask

### LINKED ISSUE #1426: BuildPluginTask is Cacheable
**Describe the bug**
`BuildPluginTask` has caching enabled, even though it is a `Zip` task and [zip tasks are not cacheable because they are not worth caching](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/tasks/bundling/Zip.java#L38). Caching I/O-bound tasks in general, like `Zip`, `Copy`, etc., can have a negative effect on performance.

**To Reproduce**
In a project using `gradle-intellij-plugin`, run the `buildPlugin` task, and Gradle will attempt to retrieve the task output from the cache.

[This build scan](https://scans.gradle.com/s/lqxfbjqoqg3fy/timeline?details=r46nrzziw6hym&expanded=WyIxIl0) shows the attempted read from cache.

**Expected behavior**
`BuildPluginTask` should have caching disabled, and should not attempt to read from the cache.

**Environment:**
 - OS: macOs
 - Gradle IntelliJ Plugin Version 1.15.0
 - Gradle Version 8.2.1

### PR DESCRIPTION
**Pull request by tylerbertrand**
# Pull Request Details

Disable caching for `BuildPluginTask`

## Description

Disable caching for `BuildPluginTask` because it is a `Zip` task. I/O bound tasks, like `Zip`, can have a negative effect on performance when cached. For this reason, [zip tasks have caching disabled by default](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/tasks/bundling/Zip.java#L38).

## Related Issue

Resolves #1426

## Motivation and Context

Being an I/O bound task, caching `BuildPluginTask` can have a negative effect on performance.

## How Has This Been Tested

* [clean test](https://ge.jetbrains.com/s/ekdimh5vo6v46)
* [clean integrationTest](https://ge.jetbrains.com/s/debcoo4ijeiw2)
* Published `gradle-intellij-plugin` with changes applied to maven local. Importing the plugin in another project, ran `buildPlugin`, and [verified `buildPlugin` had caching disabled](https://scans.gradle.com/s/3qjpb4i42phle)

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [**CONTRIBUTING**](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the [documentation](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html).
- [ ] I have updated the documentation accordingly.
- [x] I have included my change in the [**CHANGELOG**](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/CHANGELOG.md).
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/main/kotlin/org/jetbrains/intellij/tasks/BuildPluginTask.kt [hunk 1]
```diff
@@ -11,7 +11,6 @@ import org.jetbrains.intellij.IntelliJPluginConstants
  *
  * @see [Zip]
  */
```
Comment (runningcode) [inline src/main/kotlin/org/jetbrains/intellij/tasks/BuildPluginTask.kt:13]:
```suggestion
 */
 @DisableCachingByDefault(because = "Zip based tasks do not benefit from caching")
```

**Review by runningcode — CHANGES_REQUESTED** [review]

**Comment by hsz** [comment]
Thanks, folks!
