### PR TITLE
Fix tools.jar path for jbre.

### LINKED ISSUE #307: Exception when using Java 10
The kotlin plugin failed to load, error looks like Java 10ish. I'm confused, the IDE should be running the bundled jdk right?  

Building against: `2018.2`, kotlin `1.2.51` and Java 10.

```
Plugin 'org.jetbrains.kotlin' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/sun/jdi/ObjectCollectedException
    at com.intellij.debugger.settings.DebuggerSettings.loadState(DebuggerSettings.java:124)
    at com.intellij.debugger.settings.DebuggerSettings.loadState(DebuggerSettings.java:28)
    at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:356)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:312)
    at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:115)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
    at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:15)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:212)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:247)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:214)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:47)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
    at com.intellij.debugger.settings.DebuggerSettings.getInstance(DebuggerSettings.java:97)
    at org.jetbrains.kotlin.idea.debugger.filter.DebuggerFiltersUtilKt.addKotlinStdlibDebugFilterIfNeeded(DebuggerFiltersUtil.kt:27)
    at org.jetbrains.kotlin.idea.JvmPluginStartupComponent.initComponent(JvmPluginStartupComponent.java:41)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:488)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:442)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:449)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:401)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:387)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:72)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.sun.jdi.ObjectCollectedException
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:224)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 45 more
```

### PR DESCRIPTION
**Pull request by raniejade**
Also removed the lines adding the tools.jar of the JVM gradle is run on. Haven't tested it locally yet, having trouble running the tests. @zolotov can you guide me on this? Need to somehow publish to plugin locally and test it out against the spek repo. 

Resolves #307.

### CODE REVIEW

File: src/main/groovy/org/jetbrains/intellij/tasks/RunIdeTask.groovy [hunk 1]
```diff
@@ -129,9 +129,7 @@ class RunIdeTask extends JavaExec {
     private void configureClasspath() {
         File ideaDirectory = getIdeaDirectory()
         def executable = getExecutable()
-        if (executable) classpath += project.files("${new File(executable).parent}/../../lib/tools.jar")
-        def toolsJar = Jvm.current().toolsJar
-        if (toolsJar != null) classpath += project.files(toolsJar)
+        if (executable) classpath += project.files("${new File(executable).parent}/../lib/tools.jar")
```
Comment (zolotov) [inline src/main/groovy/org/jetbrains/intellij/tasks/RunIdeTask.groovy]: What if executable is not set?
Are you sure about the path to tools jar in different jre (JetBrains and oracle) for different oses?

Comment (raniejade) [reply src/main/groovy/org/jetbrains/intellij/tasks/RunIdeTask.groovy]: Based on this https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jdkfiles.html , it's safe to assume  about the path to `tools.jar`. Looks like jbre is using the same layout.

Comment (raniejade) [reply src/main/groovy/org/jetbrains/intellij/tasks/RunIdeTask.groovy]: @zolotov done. I've opted out on updating the changelog 😂 .
